package com.tiantian.mapper;

import com.tiantian.entity.Air;

import java.util.List;

public interface AirMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int insert(Air record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    Air selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    List<Air> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int updateByPrimaryKey(Air record);
}