package com.tiantian.mapper;


import com.tiantian.entity.Images;

import java.util.List;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Wed Jul 08 09:33:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Wed Jul 08 09:33:33 CST 2020
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Wed Jul 08 09:33:33 CST 2020
     */
    Images selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Wed Jul 08 09:33:33 CST 2020
     */
    List<Images> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Wed Jul 08 09:33:33 CST 2020
     */
    int updateByPrimaryKey(Images record);
}