package com.tiantian.mapper;

import com.tiantian.entity.News;

import java.util.List;

public interface NewsMapper {

    List<News> searchNews(String newsName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Fri May 29 16:20:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Fri May 29 16:20:54 CST 2020
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Fri May 29 16:20:54 CST 2020
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Fri May 29 16:20:54 CST 2020
     */
    List<News> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Fri May 29 16:20:54 CST 2020
     */
    int updateByPrimaryKey(News record);
}