package com.tiantian.mapper;

import com.tiantian.entity.Predict;

import java.util.List;

public interface PredictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int insert(Predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    Predict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    List<Predict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int updateByPrimaryKey(Predict record);
}