package com.tiantian.mapper;

import com.tiantian.entity.Real;

import java.util.List;

public interface RealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    int insert(Real record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    Real selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    List<Real> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    int updateByPrimaryKey(Real record);
}