package com.tiantian.mapper;

import com.tiantian.entity.Warn;

import java.util.List;

public interface WarnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warn
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warn
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int insert(Warn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warn
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    Warn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warn
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    List<Warn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warn
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    int updateByPrimaryKey(Warn record);
}