package com.tiantian.entity;

import java.util.Date;

public class Air {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.aq
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer aq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.aqiTest
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String aqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.text
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String forecasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.id
     *
     * @return the value of air.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.id
     *
     * @param id the value for air.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.city_id
     *
     * @return the value of air.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.city_id
     *
     * @param cityId the value for air.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.aq
     *
     * @return the value of air.aq
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getAq() {
        return aq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.aq
     *
     * @param aq the value for air.aq
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setAq(Integer aq) {
        this.aq = aq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.aqiTest
     *
     * @return the value of air.aqiTest
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getAqi() {
        return aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.aqiTest
     *
     * @param aqi the value for air.aqiTest
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setAqi(String aqi) {
        this.aqi = aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.text
     *
     * @return the value of air.text
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.text
     *
     * @param text the value for air.text
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air.forecasttime
     *
     * @return the value of air.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getForecasttime() {
        return forecasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air.forecasttime
     *
     * @param forecasttime the value for air.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setForecasttime(String forecasttime) {
        this.forecasttime = forecasttime;
    }
}