package com.tiantian.entity;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.code
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.name
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.province_id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.url
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.code
     *
     * @return the value of city.code
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.code
     *
     * @param code the value for city.code
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.name
     *
     * @return the value of city.name
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.name
     *
     * @param name the value for city.name
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.province_id
     *
     * @return the value of city.province_id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.province_id
     *
     * @param provinceId the value for city.province_id
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.url
     *
     * @return the value of city.url
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.url
     *
     * @param url the value for city.url
     *
     * @mbggenerated Wed Aug 12 16:04:09 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}