package com.tiantian.entity;

import java.util.Date;

public class Meteorological {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.humidity
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.pressure
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.rain1h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer rain1h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.rain6h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer rain6h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.rain12h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer rain12h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.rain24h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer rain24h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.tempDiff
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Double tempdiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.time
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.windDirection
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Double winddirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological.windSpeed
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Double windspeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.id
     *
     * @return the value of meteorological.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.id
     *
     * @param id the value for meteorological.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.city_id
     *
     * @return the value of meteorological.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.city_id
     *
     * @param cityId the value for meteorological.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.humidity
     *
     * @return the value of meteorological.humidity
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.humidity
     *
     * @param humidity the value for meteorological.humidity
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setHumidity(Integer humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.pressure
     *
     * @return the value of meteorological.pressure
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.pressure
     *
     * @param pressure the value for meteorological.pressure
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setPressure(Integer pressure) {
        this.pressure = pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.rain1h
     *
     * @return the value of meteorological.rain1h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getRain1h() {
        return rain1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.rain1h
     *
     * @param rain1h the value for meteorological.rain1h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setRain1h(Integer rain1h) {
        this.rain1h = rain1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.rain6h
     *
     * @return the value of meteorological.rain6h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getRain6h() {
        return rain6h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.rain6h
     *
     * @param rain6h the value for meteorological.rain6h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setRain6h(Integer rain6h) {
        this.rain6h = rain6h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.rain12h
     *
     * @return the value of meteorological.rain12h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getRain12h() {
        return rain12h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.rain12h
     *
     * @param rain12h the value for meteorological.rain12h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setRain12h(Integer rain12h) {
        this.rain12h = rain12h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.rain24h
     *
     * @return the value of meteorological.rain24h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getRain24h() {
        return rain24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.rain24h
     *
     * @param rain24h the value for meteorological.rain24h
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setRain24h(Integer rain24h) {
        this.rain24h = rain24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.tempDiff
     *
     * @return the value of meteorological.tempDiff
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Double getTempdiff() {
        return tempdiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.tempDiff
     *
     * @param tempdiff the value for meteorological.tempDiff
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setTempdiff(Double tempdiff) {
        this.tempdiff = tempdiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.temperature
     *
     * @return the value of meteorological.temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.temperature
     *
     * @param temperature the value for meteorological.temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.time
     *
     * @return the value of meteorological.time
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.time
     *
     * @param time the value for meteorological.time
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.windDirection
     *
     * @return the value of meteorological.windDirection
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Double getWinddirection() {
        return winddirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.windDirection
     *
     * @param winddirection the value for meteorological.windDirection
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setWinddirection(Double winddirection) {
        this.winddirection = winddirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological.windSpeed
     *
     * @return the value of meteorological.windSpeed
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Double getWindspeed() {
        return windspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological.windSpeed
     *
     * @param windspeed the value for meteorological.windSpeed
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setWindspeed(Double windspeed) {
        this.windspeed = windspeed;
    }
}