package com.tiantian.entity;

import java.util.Date;

public class Predict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.day_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer dayImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.day_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String dayInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.day_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String dayTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.day_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String dayDirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.day_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String dayPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.night_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer nightImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.night_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String nightInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.night_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String nightTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.night_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String nightDirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.night_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String nightPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.date
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String forecasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.id
     *
     * @return the value of predict.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.id
     *
     * @param id the value for predict.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.city_id
     *
     * @return the value of predict.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.city_id
     *
     * @param cityId the value for predict.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.day_img
     *
     * @return the value of predict.day_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getDayImg() {
        return dayImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.day_img
     *
     * @param dayImg the value for predict.day_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDayImg(Integer dayImg) {
        this.dayImg = dayImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.day_info
     *
     * @return the value of predict.day_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getDayInfo() {
        return dayInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.day_info
     *
     * @param dayInfo the value for predict.day_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDayInfo(String dayInfo) {
        this.dayInfo = dayInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.day_temperature
     *
     * @return the value of predict.day_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getDayTemperature() {
        return dayTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.day_temperature
     *
     * @param dayTemperature the value for predict.day_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDayTemperature(String dayTemperature) {
        this.dayTemperature = dayTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.day_direct
     *
     * @return the value of predict.day_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getDayDirect() {
        return dayDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.day_direct
     *
     * @param dayDirect the value for predict.day_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDayDirect(String dayDirect) {
        this.dayDirect = dayDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.day_power
     *
     * @return the value of predict.day_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getDayPower() {
        return dayPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.day_power
     *
     * @param dayPower the value for predict.day_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDayPower(String dayPower) {
        this.dayPower = dayPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.night_img
     *
     * @return the value of predict.night_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getNightImg() {
        return nightImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.night_img
     *
     * @param nightImg the value for predict.night_img
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setNightImg(Integer nightImg) {
        this.nightImg = nightImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.night_info
     *
     * @return the value of predict.night_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getNightInfo() {
        return nightInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.night_info
     *
     * @param nightInfo the value for predict.night_info
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setNightInfo(String nightInfo) {
        this.nightInfo = nightInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.night_temperature
     *
     * @return the value of predict.night_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getNightTemperature() {
        return nightTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.night_temperature
     *
     * @param nightTemperature the value for predict.night_temperature
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setNightTemperature(String nightTemperature) {
        this.nightTemperature = nightTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.night_direct
     *
     * @return the value of predict.night_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getNightDirect() {
        return nightDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.night_direct
     *
     * @param nightDirect the value for predict.night_direct
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setNightDirect(String nightDirect) {
        this.nightDirect = nightDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.night_power
     *
     * @return the value of predict.night_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getNightPower() {
        return nightPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.night_power
     *
     * @param nightPower the value for predict.night_power
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setNightPower(String nightPower) {
        this.nightPower = nightPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.date
     *
     * @return the value of predict.date
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.date
     *
     * @param date the value for predict.date
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.forecasttime
     *
     * @return the value of predict.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getForecasttime() {
        return forecasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.forecasttime
     *
     * @param forecasttime the value for predict.forecasttime
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setForecasttime(String forecasttime) {
        this.forecasttime = forecasttime;
    }
}