package com.tiantian.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.name
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.addreviation
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String addreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.id
     *
     * @return the value of province.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.id
     *
     * @param id the value for province.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.name
     *
     * @return the value of province.name
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.name
     *
     * @param name the value for province.name
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.addreviation
     *
     * @return the value of province.addreviation
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getAddreviation() {
        return addreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.addreviation
     *
     * @param addreviation the value for province.addreviation
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setAddreviation(String addreviation) {
        this.addreviation = addreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.url
     *
     * @return the value of province.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.url
     *
     * @param url the value for province.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}