package com.tiantian.entity;

public class Real {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.city_id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.airpressure
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String airpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.feelst
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String feelst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.humidity
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.info
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.rain
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private Integer rain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.temperature
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.temperature_diff
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String temperatureDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.direct
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String direct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.power
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.speed
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real.publish_time
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    private String publishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.id
     *
     * @return the value of real.id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.id
     *
     * @param id the value for real.id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.city_id
     *
     * @return the value of real.city_id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.city_id
     *
     * @param cityId the value for real.city_id
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.airpressure
     *
     * @return the value of real.airpressure
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getAirpressure() {
        return airpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.airpressure
     *
     * @param airpressure the value for real.airpressure
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setAirpressure(String airpressure) {
        this.airpressure = airpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.feelst
     *
     * @return the value of real.feelst
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getFeelst() {
        return feelst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.feelst
     *
     * @param feelst the value for real.feelst
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setFeelst(String feelst) {
        this.feelst = feelst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.humidity
     *
     * @return the value of real.humidity
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.humidity
     *
     * @param humidity the value for real.humidity
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setHumidity(String humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.info
     *
     * @return the value of real.info
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.info
     *
     * @param info the value for real.info
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.rain
     *
     * @return the value of real.rain
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public Integer getRain() {
        return rain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.rain
     *
     * @param rain the value for real.rain
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setRain(Integer rain) {
        this.rain = rain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.temperature
     *
     * @return the value of real.temperature
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.temperature
     *
     * @param temperature the value for real.temperature
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.temperature_diff
     *
     * @return the value of real.temperature_diff
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getTemperatureDiff() {
        return temperatureDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.temperature_diff
     *
     * @param temperatureDiff the value for real.temperature_diff
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setTemperatureDiff(String temperatureDiff) {
        this.temperatureDiff = temperatureDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.direct
     *
     * @return the value of real.direct
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getDirect() {
        return direct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.direct
     *
     * @param direct the value for real.direct
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setDirect(String direct) {
        this.direct = direct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.power
     *
     * @return the value of real.power
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.power
     *
     * @param power the value for real.power
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setPower(String power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.speed
     *
     * @return the value of real.speed
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.speed
     *
     * @param speed the value for real.speed
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setSpeed(String speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real.publish_time
     *
     * @return the value of real.publish_time
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real.publish_time
     *
     * @param publishTime the value for real.publish_time
     *
     * @mbggenerated Wed Aug 12 17:48:20 CST 2020
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }
}