package com.tiantian.entity;

public class Warn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.alert
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.fmeans
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String fmeans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.issuecontent
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String issuecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.pic
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.pic2
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String pic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.signallevel
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String signallevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.signaltype
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String signaltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warn.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.id
     *
     * @return the value of warn.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.id
     *
     * @param id the value for warn.id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.city_id
     *
     * @return the value of warn.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.city_id
     *
     * @param cityId the value for warn.city_id
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.alert
     *
     * @return the value of warn.alert
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.alert
     *
     * @param alert the value for warn.alert
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.fmeans
     *
     * @return the value of warn.fmeans
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getFmeans() {
        return fmeans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.fmeans
     *
     * @param fmeans the value for warn.fmeans
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setFmeans(String fmeans) {
        this.fmeans = fmeans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.issuecontent
     *
     * @return the value of warn.issuecontent
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getIssuecontent() {
        return issuecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.issuecontent
     *
     * @param issuecontent the value for warn.issuecontent
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setIssuecontent(String issuecontent) {
        this.issuecontent = issuecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.pic
     *
     * @return the value of warn.pic
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.pic
     *
     * @param pic the value for warn.pic
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.pic2
     *
     * @return the value of warn.pic2
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.pic2
     *
     * @param pic2 the value for warn.pic2
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.signallevel
     *
     * @return the value of warn.signallevel
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getSignallevel() {
        return signallevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.signallevel
     *
     * @param signallevel the value for warn.signallevel
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setSignallevel(String signallevel) {
        this.signallevel = signallevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.signaltype
     *
     * @return the value of warn.signaltype
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getSignaltype() {
        return signaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.signaltype
     *
     * @param signaltype the value for warn.signaltype
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setSignaltype(String signaltype) {
        this.signaltype = signaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warn.url
     *
     * @return the value of warn.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warn.url
     *
     * @param url the value for warn.url
     *
     * @mbggenerated Wed Aug 12 15:05:53 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}